-- Schema do catálogo de imóveis — Turso (libSQL/SQLite)
-- Banco: catalogo-imoveis
--
-- Execute uma instrução por vez (o cliente Turso não aceita
-- múltiplas statements em uma única chamada).

CREATE TABLE IF NOT EXISTS imoveis (
  codigo TEXT PRIMARY KEY,
  filial TEXT,
  codigo_cliente TEXT,
  codigo_auxiliar TEXT,
  tipo_imovel TEXT,
  subtipo_imovel TEXT,
  finalidade TEXT,
  categoria_imovel TEXT,
  titulo TEXT,
  url_portal TEXT,
  pais TEXT,
  estado TEXT,
  cidade TEXT,
  bairro TEXT,
  bairro_oficial TEXT,
  regiao TEXT,
  endereco TEXT,
  numero_endereco TEXT,
  complemento TEXT,
  cep TEXT,
  latitude REAL,
  longitude REAL,
  nome_condominio TEXT,
  condominio_fechado INTEGER,
  status_anuncio TEXT,
  vendido_alugado INTEGER,
  tipo_oferta TEXT,
  publica_valores TEXT,
  exclusividade TEXT,
  valor_venda REAL,
  valor_aluguel REAL,
  preco_medio_m2 REAL,
  condominio_mes REAL,
  iptu_ano REAL,
  area_util REAL,
  area_total REAL,
  area_privativa REAL,
  quartos INTEGER,
  suites INTEGER,
  banheiros INTEGER,
  salas INTEGER,
  vagas INTEGER,
  vagas_cobertas INTEGER,
  numero_andar INTEGER,
  total_andares INTEGER,
  ano_construcao INTEGER,
  ano_reforma INTEGER,
  precisa_reforma INTEGER,
  padrao_imovel TEXT,
  padrao_localizacao TEXT,
  ocupacao TEXT,
  ocupador TEXT,
  face_imovel TEXT,
  aceita_negociacao INTEGER,
  aceita_financiamento INTEGER,
  aceita_pet INTEGER,
  descricao TEXT,
  beneficios TEXT,
  ar_condicionado INTEGER,
  varanda_gourmet INTEGER,
  varanda INTEGER,
  piscina INTEGER,
  sauna INTEGER,
  quadra_poliesportiva INTEGER,
  wc_empregada INTEGER,
  escritorio INTEGER,
  armario_corredor INTEGER,
  armario_sala INTEGER,
  armario_cozinha INTEGER,
  armario_area_servico INTEGER,
  carpete_acrilico INTEGER,
  churrasqueira INTEGER,
  hidromassagem INTEGER,
  quintal INTEGER,
  area_servico INTEGER,
  copa INTEGER,
  lavabo INTEGER,
  deposito INTEGER,
  portao_eletronico INTEGER,
  armario_closet INTEGER,
  interfone INTEGER,
  servico_cozinha INTEGER,
  armario_dormitorio INTEGER,
  armario_banheiro INTEGER,
  corretor_nome TEXT,
  corretor_email TEXT,
  corretor_telefone TEXT,
  corretor_celular TEXT,
  foto_principal_url TEXT,
  fotos_urls TEXT,
  criacao TEXT,
  ultima_atualizacao TEXT,
  data_atualizacao_imovel TEXT,
  updated_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_imoveis_ultima_atualizacao ON imoveis(ultima_atualizacao);
CREATE INDEX IF NOT EXISTS idx_imoveis_status_anuncio ON imoveis(status_anuncio);
CREATE INDEX IF NOT EXISTS idx_imoveis_cidade_bairro ON imoveis(cidade, bairro);
CREATE INDEX IF NOT EXISTS idx_imoveis_finalidade ON imoveis(finalidade);
CREATE INDEX IF NOT EXISTS idx_imoveis_tipo_imovel ON imoveis(tipo_imovel);
